### PR TITLE
Validation first pass for RUS Form 7 and 12 tables

### LINKED ISSUE #4887: Validate USDA RUS Form 7: Distribution Tables
### `core_rus7__yearly_employee_statistics` ✔️ 
- [x] all employee and employee columns >0
- [x] employee hours worked should not be greater than employees * regular time schedule
- [x] added some expected change consistency

### `core_rus7__yearly_meeting_and_board` ✔️ 
- [x] report date > last annual meeting date
- [x] members present + voting < total members
- [x] numeric columns are positive

### `core_rus7__yearly_energy_efficiency` 🟡 
- [x] customer count is positive where cumulative
- [x] invested value is positive
- [x] savings is positive
- [ ] *TODO*: savings is not unreasonable - more complicated, still need to think about this - see below.

Todos:
Investigate probably wrong units for savings_mmbtu. there are 20 records that are reported by borrowers in years where the savings is reported in an int larger than the Int64 type... which really seems like a problem of scale.
```python
# Found bc of this error:
# pyarrow.lib.ArrowInvalid: ('Integer value 4989470342 not in range: -2147483648 to 2147483647', 'Conversion failed for column savings_mmbtu with type Int64')
df = defs.load_asset_value("core_rus7__yearly_energy_efficiency")
idx = ["borrower_id_rus","report_date"]
df = df.set_index(idx)
too_big_borrower_years = df[df.savings_mmbtu > 2147483647].sort_values(by="savings_mmbtu").index.unique()
df.loc[too_big_borrower_years].sort_index()
```

### `core_rus7__yearly_investments` ✔️ 
- Both included and excluded investments and the income_or_loss column often contain negative values. This seems sensible, and is not a validation problem. No additional validations added here.

### `core_rus7__yearly_long_term_debt` ✔️

- [x] Expect values are positive
- [x] Expect principal + interest sum to current year total

### `core_rus7__yearly_patronage_capital` ✔️

- [x] Numeric values are positive
- [x] Patronage current year > patronage cumulative
- Validate totals are sum of components -- skipped for now

### `core_rus7__yearly_power_requirements` ✔️

- [x] Numeric values are positive
- [x] Converted `is_coincident_peak` to boolean column from 0/1

### `core_rus7__scd_borrowers` 🟡 
- [x] Are all states actual states? - Yes, but also include territories,  "MH" (Marshall Islands), and "FM" (micronesia). Updated field description for source and added enum.
- [x] Assess scale of name typos - how far is this from an entity table? 500 borrowers have >1 spelling of their ID, mostly assn vs association etc.
- [ ] TODO: Explore light name standardization towards entity table

### `core_rus7__yearly_balance_sheet_liabilities` 🟡 
- [ ] TODO: Ask partners for thoughts on column-level checks here
- [ ] TODO: Consider validating "do components sum to total"

### `core_rus7__yearly_balance_sheet_assets` 🟡
- [ ] TODO: Ask partners for thoughts on column-level checks here
- [ ] TODO: Consider validating "do components sum to total"

### `core_rus7__yearly_statement_of_operations` 🟡 
- [ ] TODO: Check that opex spending is positive - it is not, and there are clear differences between + and - reporting for the `total_minus` field.
- [x] TODO: Check that monthly spending is ~1/12 of the YTD budget (5-20% range) - 20% of the data violates this constraint, is this still useful to check?
- [x] TODO: Check that budgeted spending is roughly equal to the YTD budget (75-125% range) - 20% of the data violates this constraint, is this still useful to check?
- [ ] TODO: Any other constraints here that are clear to check?

## Still to do

`core_rus7__yearly_balance_sheet_liabilities`
- investigate 25% of the values in the `balance` column are negative. from [this flag](https://github.com/catalyst-cooperative/pudl/pull/4939#discussion_r2695181270)

`core_rus7__yearly_balance_sheet_assets`
- `balance` should be a float, not an object
- 25% of data is <0

### Notes

* **core_rus7__scd_borrowers**:
   * is *[*region_code**](https://github.com/catalyst-cooperative/pudl/pull/4939#discussion_r2694999067) helpful? what is it? N/S?
   * is [**base_year**](https://github.com/catalyst-cooperative/pudl/pull/4939#discussion_r2695191832) helpful? seems like no to me
* many tables:
   *  sum/validate/drop totals

### PR DESCRIPTION
**Pull request by e-belfer**
# Overview

Closes #4887 and #4888 

## What problem does this address?
- Add a suite of validation tests for the RUS Form 7 and 12 tables
- Fix dtype issues identified during validation
- Fix other column issues identified during validation

## What did you change?
- Wrote DBT models
- Wrote generic DBT tests
- Fixed field metadata and schemas as needed, which involved recreating the migrations from scratch

## Out of scope
- Name harvesting
- Foreign key checks for the RUS IDs
- Intertable value checks (e.g., is information consistent across tables when reported in more than one place)?
- Totals validations against sub-components

## Documentation

Make sure to update relevant aspects of the documentation:

- [ ] Update the [release notes](https://catalystcoop-pudl.readthedocs.io/en/nightly/release_notes.html): reference the PR and related issues.
- [ ] Update relevant Data Source jinja templates (see `docs/data_sources/templates`).
- [ ] Update relevant table or source description metadata (see `src/metadata`).
- [ ] Review and update any other aspects of the documentation that might be affected by this PR.

# Testing

How did you make sure this worked? How can a reviewer verify this?
Recreate your DB and update the data. Then, you can run `dbt_helper validate --asset-select group:core_rus12` (and the same for rus7) to run all these checks against the updated tables.

## To-do list
- [x] Review the PR yourself and call out any questions or issues you have.

### CODE REVIEW

File: dbt/macros/expect_column_ratio.sql [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+
+  {% set column_list = adapter.get_columns_in_relation(model) | map(attribute="name") | list %}
+
+  WITH ratio_check AS (
+    SELECT
+      *,
+      CASE
+        WHEN {{ denominator_column }} IS NULL OR {{ denominator_column }} = 0
+        THEN NULL
+        ELSE {{ numerator_column }} / NULLIF({{ denominator_column }}, 0)
```
Comment (cmgosnell) [inline dbt/macros/expect_column_ratio.sql]: total nit but does this `NULLIF` need to be here if you've already `{{ denominator_column }} = 0` above?

File: dbt/macros/expect_columns_ratio.sql
Comment (cmgosnell) [inline dbt/macros/expect_columns_ratio.sql:1]: 1000% nit but i think this would be more clear if it was `expect_columns_ratio`

File: dbt/models/rus7/core_rus7__yearly_balance_sheet_assets/schema.yml
Comment (cmgosnell) [inline dbt/models/rus7/core_rus7__yearly_balance_sheet_assets/schema.yml:1]: should we add a threshold or a `expect_column_min_to_be_between` for `balance`? or i suppose balance is just probably expected to be negative sometimes. (same question for the liabilities).

This should be totally oos but I also wonder if the finance peeps at RMI could give us some insight into expected proportional values for particular `asset_type`'s compared to others (like whatever `utility_plant_in_service` shouldn't normally be more than X% of `total`

File: dbt/models/rus7/core_rus7__yearly_energy_efficiency/schema.yml [hunk 2]
```diff
@@ -3,12 +3,30 @@ sources:
...
+                  arguments:
+                    min_value: 0.0
           - name: savings_mmbtu
+            data_tests:
+              - dbt_expectations.expect_column_min_to_be_between:
+                  arguments:
+                    min_value: 0.0
+                  config:
+                    error_if: ">8"
+                  description: "KS0059 has negative values which don't follow from prior years of data." #TODO
```
Comment (cmgosnell) [inline dbt/models/rus7/core_rus7__yearly_energy_efficiency/schema.yml:32]: this is the column that probably imu has unit errors embedded in there.

File: dbt/macros/expect_summed_columns_not_exceed_threshold.sql
Comment (cmgosnell) [inline dbt/macros/expect_summed_columns_not_exceed_threshold.sql:1]: total naming nit that you can take or leave but i think this would be easier to understand as `expect_summed_columns_not_exceed_threshold`

**Review by cmgosnell — COMMENTED** [review]
this is looking amazing. took me a little longer than i'd desire to parse through the sql but that's my level of sql not what's going on in there. I see your todo list in the issue and i think this all looks like its moving in the right direction.

On a meta level, it seems we should compile all of the investigate/TODO's and organize them in rough priority and share them with RMI/RPC. Many of them imho seems super low priority, just nice to know.

File: dbt/models/rus7/core_rus7__yearly_balance_sheet_assets/schema.yml
Comment (e-belfer) [reply dbt/models/rus7/core_rus7__yearly_balance_sheet_assets/schema.yml:1]: Absolutely - I need to fix the column names and dtypes so I haven't actually finished validating this table yet.

File: dbt/models/rus7/core_rus7__yearly_energy_efficiency/schema.yml (hunk 2 above)
Comment (e-belfer) [reply dbt/models/rus7/core_rus7__yearly_energy_efficiency/schema.yml:32]: Could check this against total energy demand reported in another table.

File: dbt/macros/expect_column_ratio.sql (hunk 1 above)
Comment (e-belfer) [reply dbt/macros/expect_column_ratio.sql]: No not necessarily, it's just a safety guard that can get removed.

File: dbt/models/rus7/core_rus7__yearly_balance_sheet_assets/schema.yml
Comment (e-belfer) [reply dbt/models/rus7/core_rus7__yearly_balance_sheet_assets/schema.yml:1]: Open question as to what the useful validations would be here, as this is very often negative.

File: dbt/models/rus12/core_rus12__yearly_sources_and_distribution_by_plant_type/schema.yml [hunk 3]
```diff
@@ -11,6 +11,24 @@ sources:
...
+              - dbt_expectations.expect_column_min_to_be_between:
+                  arguments:
+                    min_value: 0.0
           - name: net_energy_received_mwh
+            data_tests:
+              - dbt_expectations.expect_column_min_to_be_between:
+                  arguments:
+                    min_value: 0.0
+                  config:
+                    error_if: ">24" #TODO: Almost entirely explained by GA0109 (hydro plant)
```
Comment (cmgosnell) [inline dbt/models/rus12/core_rus12__yearly_sources_and_distribution_by_plant_type/schema.yml:34]: non-blocking but maybe we should exclude plant_type hydro from this?

File: dbt/models/rus12/core_rus12__yearly_statement_of_operations/schema.yml [hunk 4]
```diff
@@ -3,13 +3,51 @@ sources:
...
           - name: borrower_name_rus
           - name: opex_type
           - name: opex_group
           - name: opex_report_month
+            data_tests:
+              - dbt_expectations.expect_column_min_to_be_between:
+                  arguments:
+                    min_value: 0.0
+                  config:
+                    error_if: ">650" # TODO: ~3.7% of data violates this. Worth checking?
```
Comment (cmgosnell) [inline dbt/models/rus12/core_rus12__yearly_statement_of_operations/schema.yml]: in my general understanding it is possible - albeit rare - to have negative opex values. and there are clearly patterns here for which fields are negative:

Image

Image

Comment (cmgosnell) [reply dbt/models/rus12/core_rus12__yearly_statement_of_operations/schema.yml]: it seems like at the very least we should add this row condition to all of these checks and reduce the # of exceptions:
`row_condition: "opex_type != 'interest_charged_to_construction_credit'"`


Image

File: dbt/models/rus7/core_rus7__yearly_statement_of_operations/schema.yml
Comment (cmgosnell) [inline dbt/models/rus7/core_rus7__yearly_statement_of_operations/schema.yml:1]: oof this table looks confusing to test to say the least.

looking at `opex_ytd` here in the same fashion as i was for the rus12 version of this table - the # of negative records: 
Image
and the portion of negative records:

Image

If we want to keep these expect not negative tests, then we should almost certainly remove `opex_group IN ("patronage_capital_or_margins", "patronage_and_operating_margins")` and it seems also `opex_type != "interest_charged_to_construction"` but even for the `opex_ytd` that would still leave 659 negative values :-/ _only_ 149 for `opex_ytd_budget`

it might just be that this table requires some deeper documentation or we should ask deeper subject experts what are more nuanced expectations of this table

File: dbt/models/rus12/core_rus12__yearly_sources_and_distribution_by_plant_type/schema.yml (hunk 3 above)
Comment (e-belfer) [reply dbt/models/rus12/core_rus12__yearly_sources_and_distribution_by_plant_type/schema.yml:34]: The vast majority of hydro data (at least from the 25th percentile) is positive, so I think the flag here is weird plant rather than weird plant type.

File: dbt/models/rus12/core_rus12__yearly_statement_of_operations/schema.yml (hunk 4 above)
Comment (e-belfer) [reply dbt/models/rus12/core_rus12__yearly_statement_of_operations/schema.yml]: For all three numeric fields the 75th percentile of this opex type is negative or 0, so I agree with this and have excluded it from the test.

File: dbt/models/rus7/core_rus7__yearly_statement_of_operations/schema.yml
Comment (e-belfer) [reply dbt/models/rus7/core_rus7__yearly_statement_of_operations/schema.yml:1]: Looking at the percentiles of negative data, I'm seeing that ~23% of patronage_capital_or_margins data is negative, and ~55% of the interest charged to construction. For now, I'm going to adopt your suggestion but I'll leave a to do in here to look into this further.
